name: infractions_inspector
description: "App to track infractions by agent."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_form_builder: ^10.0.1
  dropdown_search: ^6.0.2
  pdf: ^3.11.3
  printing: ^5.14.2
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jefaturas.json
    - assets/agentes.json
    - assets/conceptos.json
    - assets/reglamento.txt
    - assets/images/logo.png
